### ISSUE TITLE
Compiling with unmodified toolchain.

### ISSUE THREAD

**Issue by ethanrjones97** [neon-orb/project-asiago#5]
Ideally, we could just use an unmodified `gcc` and `binutils` instead of having to cross-compile.

**Comment by chris13524** [comment]
Is this possible? According to the OS Dev [wiki](http://wiki.osdev.org/GCC_Cross-Compiler), we need a cross compiler. The same architecture is one thing, but it appears it needs the same operating system.

**Comment by ethanrjones97** [comment]
Yup, it seems it's essential when building an OS, too bad.
http://wiki.osdev.org/Why_do_I_need_a_Cross_Compiler
