### ISSUE TITLE
Final Link Failed

### ISSUE THREAD

**Issue by bms-1984** [neon-orb/project-asiago#7]
I've gotten myself a x86_64-elf-\* toolchain and tried building Feta, Mish, and Aura with and without it. Everything builds, but when I use "make run" in the Aura directory, I get

`ld: gnu-efi/libs/libefi.a(str.o): unrecognized relocation (0x2a) in section '.text'
ld: final link failed: Bad Value`

I'm not knowledgable about linking so I don't know what this could mean. I've installed Qemu, also. I'm very interested in contributing to this project, but I can't seem to build it. Thank you for your time

_Ben_

**Comment by chris13524** [comment]
Did you try following the instructions on the main project page? It should not require any special toolchains.

https://github.com/neonorb/project-asiago

**Comment by bms-1984** [comment]
Oh, it can all be done from there? I missed that. Thanks.

**Comment by chris13524** [comment]
Yes, unless I'm missing something about your specific setup, it should automatically download and build everything that's required. I generally don't even run `make` in any of the subprojects (aura, mish, etc.), I let the main one handle it all.

Let me know if it works! :)

**Comment by bms-1984** [comment]
Alright, getting the same error that way...

**Comment by bms-1984** [comment]
My setup isn't special. The strange part of my setup is that I'm currently running GuixSD so programs are installed in weird places, but they're run the same way, so I can't see that affecting this...

**Comment by chris13524** [comment]
Would you mind posting the full output on a Gist/Pastebin?

**Comment by bms-1984** [comment]
Okay, will do.

**Comment by bms-1984** [comment]
https://gist.github.com/BenjaminSutter/137d9af62c3cbde55a88e045a491ebd3

**Comment by chris13524** [comment]
I'm assuming you are on a x86_64 system?

**Comment by bms-1984** [comment]
Yes.

**Comment by chris13524** [comment]
I have no idea if this will work, but could you try adding this flag to `aura/makefile`? Make sure you remember the backslash (`\`). Then rebuild with `make clean; make run`.

![z4yjsyd](https://cloud.githubusercontent.com/assets/1979423/18812034/b65e562c-8294-11e6-9209-0fa6c06bb991.png)

**Comment by bms-1984** [comment]
Nope, no difference. Hmmm.

**Comment by chris13524** [comment]
You wouldn't happen to have another Linux machine you could test this on, do you? It works fine with default Ubuntu installations on my machines.

**Comment by bms-1984** [comment]
I could (relatively) easily just install Ubuntu because, no, I have literally no other computers. I'll do that, I guess.

**Comment by chris13524** [comment]
You could try a VM, I'm guessing it's something odd with your setup.

**Comment by bms-1984** [comment]
I don't have anything important on this installation, plus it breaks a lot of other stuff. I'll get a copy of Ubuntu and get back to you.

**Comment by chris13524** [comment]
I'm not very knowledgeable on this area either, it's mostly just guess and check for me.

**Comment by bms-1984** [comment]
It works on Ubuntu. Do you have anything you need done or should I just figure out some stuff to add?

**Comment by bms-1984** [comment]
When running in Qemu, what does it mean to get incorrect parse mode? Does that just mean that the command is invalid? What commands exist?

**Comment by bms-1984** [comment]
For instance, how is the Pong command run?

**Comment by chris13524** [comment]
You are dropped to a Mish interpreter. The available syscalls are added in here: `implementation/system/syscalls.cpp`.

Pong is not an actual command, it's a different implementation. The current one being `auramain`. You can switch it to pong in this file: `implementation/implementation.cpp`, although it's likely not to work.

**Comment by bms-1984** [comment]
Okay, thank you. I'm just trying to figure out the setup.

**Comment by chris13524** [comment]
It's not intended to be similar to other OSs, so things will be very different.

I'm sort of figuring out the direction I want to go with much of the Mish stuff, but if you want to work on something, you could write a mouse module :)

**Comment by chris13524** [comment]
Hopefully you can understand how those work from the keyboard and screen modules.

**Comment by bms-1984** [comment]
I know nothing about mice, but I'll try try figure that out.

**Comment by bms-1984** [comment]
There's probably a better way to talk than this issue, too.

**Comment by chris13524** [comment]
Talk to you in Telegram.

**Comment by bms-1984** [comment]
Okay.
